# Generated by Django 2.0.1 on 2018-03-05 12:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cell_phone', models.CharField(max_length=15)),
                ('avatar_url', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'گروه', 'verbose_name_plural': 'گروه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'دخل و خرج', 'verbose_name_plural': 'دخل و خرج'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ', 'verbose_name_plural': 'تگ\u200cها'},
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('In', 'درآمد'), ('Exp', 'هزینه')], max_length=3),
        ),
    ]
