# Generated by Django 2.1.3 on 2018-12-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_auto_20181212_1642'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name', 'date'], name='Accounting__name_152cb8_idx'),
        ),
    ]
